### ISSUE TITLE
Nomad v0.5.0 support

### ISSUE THREAD

**Issue by tmichaud314** [nathwill/chef-nomad#18]
Hi @nathwill - Do you have plans to add support for v0.5.0?  Thanks!

**Comment by nathwill** [comment]
Yep, absolutely! I just got back from vacation, so a bit behind, but planning to dig into 0.5.0 next week when the holiday's done (persistent disk, yay!). If you need it sooner, PR's are welcome, and I could probably get a review/merge done this week.

**Comment by tmichaud314** [comment]
Excellent, thank you.  Glad to test it out for you.

**Comment by nathwill** [comment]
@tmichaud314 this just went out in 0.10.0, wanna take it for a spin?

**Comment by tmichaud314** [comment]
@nathwill Sure!  Sorry for the delay.  Missed your email.

**Comment by evan2645** [comment]
FWIW, we've been running latest nomad without issue

**Comment by tmichaud314** [comment]
We have been using 0.10.0 now for about a week.  No issues to report!

**Comment by evan2645** [comment]
Closing this, seems to work fine. If you run into any specific problems, feel free to open a new issue
