### ISSUE TITLE
co-maintainer(s) wanted

### ISSUE THREAD

**Issue by nathwill** [nathwill/chef-nomad#19]
looking for some folks to help maintain this project, any takers?

**Comment by tyuio9** [comment]
@nathwill Why not. I'm using a bit modified version of this cookbook at my company. :-)

**Comment by nathwill** [comment]
awesome, thanks!

**Comment by evan2645** [comment]
I can keep an eye out - we are actively working on nomad w/ this cookbook

**Comment by dbresson** [comment]
If you still need more help, I'm game.

**Comment by nathwill** [comment]
awesome, thanks @dbresson! there's 4 of us now, which i think is a pretty good number, so i'm gonna close this out for now.
