### ISSUE TITLE
Nomad service failed to start on fast machines

### ISSUE THREAD

**Issue by grind42** [nathwill/chef-nomad#47]
We've got a test cluster which is running on fast VMs. After a reboot Nomad service is failed and doesn't start.
Looks like it's trying to start before network is up.
Opened the issue in case somebody else has problems like this so that they find any info to why.
Fixing this in a PR.

`Redirecting to /bin/systemctl status nomad.service
● nomad.service - Nomad Cluster Manager
   Loaded: loaded (/etc/systemd/system/nomad.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2020-09-14 11:00:29 CEST; 48s ago
     Docs: https://www.nomadproject.io/docs/index.html
  Process: 865 ExecStart=/usr/local/sbin/nomad agent -config=/etc/nomad.conf.d (code=exited, status=1/FAILURE)
 Main PID: 865 (code=exited, status=1/FAILURE)

Sep 14 11:00:29 client.domain.net nomad[865]: 2020-09-14T11:00:29.038+0200 [WARN]  client.fingerprint_mgr: failed to detect bridge kernel module, bridge network mode disabled: error="could not detect k... module bridge"
Sep 14 11:00:29 client.domain.net nomad[865]: 2020-09-14T11:00:29.038+0200 [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
Sep 14 11:00:29 client.domain.net systemd[1]: Unit nomad.service entered failed state.
Sep 14 11:00:29 client.domain.net systemd[1]: nomad.service failed.
Sep 14 11:00:29 client.domain.net systemd[1]: nomad.service holdoff time over, scheduling restart.
Sep 14 11:00:29 client.domain.net systemd[1]: Stopped Nomad Cluster Manager.
Sep 14 11:00:29 client.domain.net systemd[1]: start request repeated too quickly for nomad.service
Sep 14 11:00:29 client.domain.net systemd[1]: Failed to start Nomad Cluster Manager.
Sep 14 11:00:29 client.domain.net systemd[1]: Unit nomad.service entered failed state.
Sep 14 11:00:29 client.domain.net systemd[1]: nomad.service failed.`

**Comment by nathwill** [comment]
@grind42 thanks! this is up on supermarket in 2.3.1 now
